### ISSUE TITLE
problem while running on rpi4b

### ISSUE THREAD

**Issue by SYYANI** [gtntdev/-WifiConfigViaBluetooth-Docker#1]
in the android app, while click the scan button, it show nothing!
best wishes

**Comment by gtntdev** [comment]
Hi SYYANI,

with this little information it's hard to tell where it went wrong exactly.
To debug the application please make sure you followed the wiki and that there is no more bluetooth and wifi service running BEFORE you start the container, otherwise it wount work.
1) You can go inside the docker container (get the containers `name` with `docker ps`) with `docker exec -it name /bin/bash`
2) kill the bluetooth service script and start it manually, what's the output  while scanning?

I already tested it with a Pi4 but don't know if it was 4b and in case it wasn't Idk if it makes a differece but I don't thing so.

Best Lukas

**Comment by SYYANI** [comment]
hi Lukas,
Thank you for your reply!  I have solved this problem already, there is two points, one the the "dev.py" script in the python_server folder, an early "return" in line 93, I deleted it. The second point is "docker-compose.yml" , I add "device:
            - "/dev/wlan0:/dev/wlan0" " , that's all. 
By the way, the device I use is CM4! 
Best yiyan.
